development: &default
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: cron_job_local_test
   pool: 5
   username: root
   password: root
   host: localhost

production: &default
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: cron_job_production_test
   pool: 5
   username: root
   password: root
   host: localhost